# Generated by Django 5.2.16 on 2026-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='desired_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Желаемая должность'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio',
            field=models.URLField(blank=True, verbose_name='Портфолио'),
        ),
    ]
