# Generated by Django 5.2.17 on 2026-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('profiles', '0002_studentprofile_desired_position_and_more'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлен'), ('viewed', 'Просмотрен'), ('invited', 'Приглашение'), ('rejected', 'Отказ')], db_index=True, default='sent', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('vacancy', 'student'), name='unique_application'),
        ),
    ]
