# Generated by Django 5.2.17 on 2026-08-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст'),
        ),
    ]
