# Generated by Django 5.2.16 on 2026-07-12 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Зарплата')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('work_type', models.CharField(choices=[('remote', 'Удалённо'), ('office', 'В офисе'), ('hybrid', 'Гибрид')], default='office', max_length=10, verbose_name='Тип работы')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='vacancies.category', verbose_name='Категория')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='profiles.employerprofile')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
